#llama al programita cgdb que a su vez invoca al gdb d earm con un archivo de configuracino muyyy basico.. why? porque el cgdb es mas bonito que el gdb -tui pelado y puedo hacer shortcuts de teclado, definir breaks etc mas rapido...
cgdb -d /opt/arm-none-eabi-6/bin/arm-none-eabi-gdb -q ../exe/app.axf --command=command.gdb
